a13project/urls.py
from json.decoder import JSONDecodeError
from django import urls
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

from django.views.generic import TemplateView
from django.contrib.auth.views import LogoutView


from django.http import HttpResponse, HttpResponseRedirect

from django.views import generic
import requests
from django.template import loader

class IndexView(generic.View):
    def index(request):
        template = loader.get_template('index.html')
        quoteText=""
        quoteAuthor=""

        while True:
            try:
                response = requests.get('http://api.forismatic.com/api/1.0/?method=getQuote&format=json&lang=en')
                quote = response.json()
                quoteText = quote['quoteText']
                quoteAuthor = quote['quoteAuthor']
            except JSONDecodeError: #for some reason this api returns lots of decode errors
                continue
            break
        context = {
            'quoteText': quoteText,
            'quoteAuthor': quoteAuthor
        }
        return HttpResponse(template.render(context, request))

urlpatterns = [
    path('organizer/', include('organizer.urls')),  # the app is called organizer so it's intuitive in url
    path('admin/', admin.site.urls),
    path('', IndexView.index, name='index'),
    path('accounts/', include('allauth.urls')),
    path('logout', LogoutView.as_view(), name='logout'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

organizer/urls.py
from django.urls import path
from django.urls.resolvers import URLPattern
from django.conf.urls.static import static
from django.conf import settings

from . import views

app_name = 'organizer'  # set app namespace
urlpatterns = [
    path('', views.HomeView.home, name='home'),  # ex: /organizer/ aka homepage
    # path('login/', views.LoginView.login, name='login'),  # ex: /organizer/login/ aka login page
    # path('register/', views.register_student, name='register'),
    path('register_check/', views.checkIfStudentRegistered, name='check_register'),
    path('students/<str:class_name>/', views.StudentView.studentView, name='students'),
    path('profile/', views.ProfileView.profileView, name='profile'),  # ex: /organizer/profile/ aka profile page
    path('search/', views.SearchView.searchView, name='search'), # /organizer/search/ for class search page
    path('class/<str:class_name>/', views.ClassView.classView, name='classview'),
    path('join/<str:class_name>/', views.JoinClassView, name='join'),
    path('leave/<str:class_name>/', views.LeaveClassView, name='leave'),
    path('assignments/', views.AssignView, name='assignments'),
    path('upload/<int:notes_group>/', views.NotesUploadView, name='upload'),
    path('addGroup/', views.AddNotesGroupView, name='addGroup'),
    path('deletenotes/<int:notes_id>/', views.DeleteNotesView, name='delete_notes'),
    path('check_assignment/<int:assign_id>/', views.CheckAssignView, name='check_assign'),
    path('deleteassignment/<int:assign_id>/', views.DeleteAssignView, name='delete_assign'),
    path('populate/<int:start>/', views.populate_database_view, name='populate'),
    path('newjoke/', views.newJoke, name='joke')


] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

organizer/models.py
from datetime import timedelta
from django.db import models
from django.db.models.base import Model
from django.db.models.fields import CharField
from django.urls import reverse
from django.contrib.auth.models import User
from django import forms


# many-to-one relationship aka foreign keys: https://docs.djangoproject.com/en/3.2/topics/db/examples/many_to_one/
class Class(models.Model):
    class_name = models.CharField(max_length=10, default="", unique=True)  # assuming the string is 'CS3240'

    def __str__(self):
        return self.class_name


class Section(models.Model):
    section_id = models.CharField(max_length=10, unique=True)
    professor = models.CharField(max_length=200, default="")
    days = models.CharField(max_length=7, default="")  # ex. MWF
    start_time = models.TimeField()
    end_time = models.TimeField()
    course = models.ForeignKey(Class, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.professor.split(',')[0]} | {self.days} {self.start_time}-{self.end_time}"

    def professor_lname(self):
        return self.professor.split(',')[0]

# https://docs.djangoproject.com/en/3.2/topics/auth/customizing/
class Student(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE) # link to Django User mdoel
    schedule = models.ManyToManyField(Class)
    sections = models.ManyToManyField(Section)

    def __str__(self):
        return f"{self.user.first_name} {self.user.last_name}"


class NotesGroup(models.Model):
    title = models.CharField(max_length=100)
    course = models.ForeignKey(Class, on_delete=models.CASCADE)
    create_time = models.DateTimeField(auto_now=True)


class Notes(models.Model):
    title = models.CharField(max_length=100)
    pdf = models.FileField(upload_to='files/')
    group = models.ForeignKey(NotesGroup, on_delete=models.CASCADE)
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    date = models.DateField(auto_now=True)

    class Meta:
        ordering = ['date']

    def __str__(self):
        return f"{self.title}"


class NotesUploadForm(forms.ModelForm):
    class Meta:
        model = Notes
        fields = ('title', 'pdf',)


class Assignment(models.Model):
    class_name = models.CharField(max_length=100)
    assignment = models.CharField(max_length=200, default=" ")
    deadline = models.DateField()
    completed = models.BooleanField()
    student = models.ForeignKey(Student, on_delete=models.CASCADE)

    def ColorDeadlines(self):
        from datetime import timedelta, date
        delta = self.deadline - date.today()
        if delta <= timedelta(days=1):
            return "red" 
        elif delta > timedelta(days=1) and delta <= timedelta(days=3):
            return "yellow"
        else:
            return "green"


    def __str__(self):
        return f"{self.assignment}"

organizer/forms.py
from django import forms
from django.forms import TextInput
from django.forms.fields import EmailField
from django.forms.widgets import EmailInput, SelectDateWidget
from django.utils.regex_helper import Choice
from datetime import datetime


class RegisterForm(forms.Form):
    first_name = forms.CharField(label='First Name', widget=TextInput(attrs={'class': 'form-control'}))
    last_name = forms.CharField(label='Last Name', widget=TextInput(attrs={'class': 'form-control'}))


class ProfileUpdateForm(forms.Form):
    username = forms.CharField(label="Username", widget=TextInput(attrs={'class': 'form-control'}))
    first_name = forms.CharField(label="First Name", widget=TextInput(attrs={'class': 'form-control'}))
    last_name = forms.CharField(label="Last Name", widget=TextInput(attrs={'class': 'form-control'}))


class AssignForm(forms.Form):
    assignment = forms.CharField(widget=TextInput(attrs={'class': 'form-control'}))
    deadline = forms.DateField(widget=forms.widgets.DateInput(attrs={'type': 'date'}))


class searchForm(forms.Form):
    class_name = forms.CharField(
        label='',
        widget=TextInput(
            attrs={'class': 'form-control rounded',
                   'placeholder': "Input the Class Mneumonic and/or Class Number ex) CS, CS3240, CS 3240"})
    )
    #

organizer/views.py
from json.decoder import JSONDecodeError
from typing import Reversible
from django import template
from django.db.utils import IntegrityError
from django.http.response import HttpResponseRedirect
from django.views import generic
from django.shortcuts import redirect, render
from django.template import loader
from django.http import HttpResponse, request, JsonResponse
from django.shortcuts import get_object_or_404, render
from django.views.generic.edit import FormView
from django.urls import reverse
from .models import Class, Section, Student, Notes, NotesUploadForm, NotesGroup, Assignment
from .forms import ProfileUpdateForm, RegisterForm, AssignForm, searchForm
from django.db import IntegrityError
import requests
import json
import re
import random
from datetime import timedelta, date

def AssignView(request):
    context={}
    if request.user.is_anonymous:
        registered = False

    else:
        registered = True
        if request.method == 'POST':
            form = AssignForm(request.POST)
            if form.is_valid():
                data = form.cleaned_data
                student = request.user.student
                class_name = request.POST.get('class_name', '')
                assignment = data['assignment']
                deadline = data['deadline']
                assignment = Assignment(class_name=class_name, assignment=assignment, deadline=deadline, completed=False, student=student)
                assignment.save()
                return redirect('organizer:assignments')
        else:
            form = AssignForm()
            assignments = request.user.student.assignment_set.filter(completed=False).order_by('deadline')
            completed = request.user.student.assignment_set.filter(completed=True).order_by('deadline')
            context = {
                'assignform': form,
                'assignments': assignments,
                'completed': completed,
                'registered':registered,
            }
    return render(request, 'organizer/assignment.html', context)


class HomeView(generic.ListView):
    def home(request):
        template = loader.get_template('organizer/home.html')
        context={}
        
        if request.user.is_anonymous:
            registered = False

        else:
            registered = True
            sections = request.user.student.sections.all()
            days = {"M": [], "T": [], "W": [], "R": [], "F": []}
            for day in days:
                for section in sections:
                    if day in section.days:
                        days[day].append(section)
                days[day].sort(key=lambda s: s.start_time)

            context = {
                "classes": request.user.student.schedule.all(),
                "assignments": request.user.student.assignment_set.filter(completed=False, deadline__range=[date.today(),date.today()+timedelta(days=1)]).order_by('deadline'),
                "M": days["M"],
                "T": days["T"],
                "W": days["W"],
                "R": days["R"],
                "F": days["F"],
                "registered": registered,
            }
        return HttpResponse(template.render(context, request))


def newJoke(request):
    setup = ""
    delivery = ""
    while True:
        try:
            response = requests.get('https://v2.jokeapi.dev/joke/Programming?blacklistFlags=nsfw,racist,sexist,explicit,religious,political')
            joke = response.json()
            setup = joke['setup']
            delivery = joke['delivery']
        except KeyError:
            continue
        except JSONDecodeError:
            continue
        break
    return JsonResponse({"jokeSetup": setup, "jokeDelivery": delivery})


class ProfileView (generic.View):
    def profileView(request):
        template = 'organizer/profile.html'
        context={}
        if request.user.is_anonymous:
            registered = False

        else:
            registered = True
            if request.method == 'POST':
                form = ProfileUpdateForm(request.POST)
                if form.is_valid():
                    data = form.cleaned_data
                    user = request.user
                    user.username = data['username']
                    user.first_name = data['first_name']
                    user.last_name = data['last_name']
                    user.save()
                return redirect('organizer:profile')
            else:
                user = request.user
                data = {'username': user.username, 'first_name': user.first_name, 'last_name': user.last_name }
                form = ProfileUpdateForm(initial=data)
                context ={
                   'form': form,
                   'registered':registered, 
                }
        return render(request, template, context)


class ClassView (generic.View):
    def classView(request, class_name):
        template = loader.get_template('organizer/classview.html')
        course = Class.objects.get(class_name=class_name)
        notes_groups = course.notesgroup_set.all().order_by('-create_time')
        context = {
            'class': course,
            'notes_groups': notes_groups,
            'form': NotesUploadForm()
        }
        return HttpResponse(template.render(context, request))


class StudentView (generic.View):
    def studentView(request, class_name):
        template = loader.get_template('organizer/students.html')
        course = Class.objects.get(class_name=class_name)
        context = {
            'class': course,
            'students': course.student_set.all()
        }
        return HttpResponse(template.render(context, request))


class SearchView(generic.View):
    def searchView(request):
        template = loader.get_template('organizer/searchview.html')
        context={}
        if request.user.is_anonymous:
            registered = False

        else:
            registered = True
            classes = []
            if request.method == 'POST':
                form = searchForm(request.POST)
                if form.is_valid():
                    class_search = form.data['class_name'].upper()
                    class_search = class_search.replace(" ", "")
                    classes = Class.objects.filter(class_name__contains=class_search)
            else:
                form = searchForm()
                #classes = Class.objects.all()
                classes = request.user.student.schedule.all()
            context = {
                'classes': classes,
                'joined': request.user.student.schedule.all(),
                'form': form,
                'registered':registered,
            }
        return HttpResponse(template.render(context, request))


def JoinClassView(request, class_name):
    if request.method == 'POST':
        student = request.user.student
        course = Class.objects.get(class_name=class_name)
        student.schedule.add(course)
        section_id = request.POST.get('section', '')
        section = Section.objects.get(id=section_id)
        student.sections.add(section)
        student.save()
        return JsonResponse({'ok': True})
    return JsonResponse({'ok': False})


def LeaveClassView(request, class_name):
    if request.method == 'POST':
        student = request.user.student
        course = Class.objects.get(class_name=class_name)
        sections = student.sections.filter(course=course)
        for section in sections:
            student.sections.remove(section)
            section.student_set.remove(student)
        student.schedule.remove(course)
        course.student_set.remove(student)
        return redirect('organizer:home')
    return redirect('organizer:home')


def checkIfStudentRegistered(request):
    try:
        verification=Student.objects.get(user=request.user)
        return redirect('organizer:home')
    except Student.DoesNotExist:
        user = request.user
        new_student = Student(user=user)
        new_student.save()
        return redirect('organizer:home') 


def NotesUploadView(request, notes_group):
    if request.method == 'POST':
        form = NotesUploadForm(request.POST, request.FILES)
        if form.is_valid():
            data = form.cleaned_data
            title = data['title']
            pdf = data['pdf']
            group = NotesGroup.objects.get(id=notes_group)
            new_upload = Notes(title=title, pdf=pdf, group=group, student=request.user.student)
            new_upload.save()
    return redirect(request.META.get('HTTP_REFERER'))


def AddNotesGroupView(request):
    if request.method == 'POST':
        class_name = request.POST.get('class_name', '')
        title = request.POST.get('title', '')
        course = Class.objects.get(class_name=class_name)
        notesGroup = NotesGroup(title=title, course=course)
        notesGroup.save()
        return JsonResponse({'ok': True})
    return JsonResponse({'ok': False})


def DeleteNotesView(request, notes_id):
    if request.method == 'POST':
        Notes.objects.get(id=notes_id).delete()
        return JsonResponse({'ok': True})
    return JsonResponse({'ok': False})


def CheckAssignView(request, assign_id):
    if request.method == 'POST':
        assign = Assignment.objects.get(id=assign_id)
        completed = request.POST.get('completed', False)
        if completed == "true":
            assign.completed = True
        else:
            assign.completed = False
        assign.save()
        return JsonResponse({'ok': True})
    return JsonResponse({'ok': False})

def DeleteAssignView(request, assign_id):
    if request.method == 'POST':
        Assignment.objects.get(id=assign_id).delete()
        return JsonResponse({'ok': True})
    return JsonResponse({'ok': False})

def populate_database_view(request, start=0):
    data = requests.get('https://api.devhub.virginia.edu/v1/courses')
    #data = requests.get('http://stardock.cs.virginia.edu/louslist/Courses/')
    data.raise_for_status()

organizer/templates/organizer/assignments_list.html
<ul class="list-group">
  {% for assignment in assignments %}
  <li class ="list-group-item list-item d-flex align-items-baseline" id="assignment{{assignment.id}}">
      {% if assignment.completed %}
        <div class="form-check me-2">
            <input class="form-check-input assign-complete" type="checkbox" value="" id="completed{{assignment.id}}" checked>
            <div class="completed">
              {{ assignment.assignment }}
              {% if assignment.class_name %}
                | <a href="{% url 'organizer:classview' assignment.class_name %}"> {{assignment.class_name }} </a>
              {% endif %}
            </div>
        </div>
        <div class="ms-auto p-1 rounded {{assignment.ColorDeadlines}}" id="deadline{{assignment.id}}" style="display:none;">
            <i class="bi bi-alarm me-1"></i> {{ assignment.deadline }}
        </div>
        <div class="ms-auto p-1 rounded gray" id="deadline_complete{{assignment.id}}">
          <i class="bi bi-alarm me-1"></i> {{ assignment.deadline }}
        </div>
      {% else %}
        <div class="form-check me-2">
            <input class="form-check-input assign-complete" type="checkbox" value="" id="completed{{assignment.id}}">
            <div>
              {{ assignment.assignment }}
              {% if assignment.class_name %}
                | <a href="{% url 'organizer:classview' assignment.class_name %}"> {{assignment.class_name }} </a>
              {% endif %}
            </div>
        </div>
        <div class="ms-auto p-1 rounded {{assignment.ColorDeadlines}}" id="deadline{{assignment.id}}">
          <i class="bi bi-alarm me-1"></i> {{ assignment.deadline }}
        </div>
        <div class="ms-auto p-1 rounded gray" style="display:none;" id="deadline_complete{{assignment.id}}">
          <i class="bi bi-alarm me-1"></i> {{ assignment.deadline }}
        </div>
      {% endif %}
      <button class="btn btn-sm button-red rounded-circle ms-3" type="button" id="delete{{assignment.id}}">  <i class="bi bi-trash"></i> </button>
    </li>
    {% empty %}
    <li class="list-group-item list-item d-flex justify-content-center"><i class="bi bi-card-checklist me-1"></i> No upcoming deadlines! </li>
  {% endfor %}
</ul>

organizer/templates/organizer/classview.html
{% extends "organizer/base.html" %}
{% load static %}
{% block styles %}
    <link rel="stylesheet" href="{% static 'classview.css' %}">
{% endblock %}
{% block content %}
<div class="text-center">
    <h1 id="className">{{class.class_name}}</h1>
    <a href="{% url 'organizer:students' class.class_name %}"> <i class="bi bi-person-lines-fill"></i> {{ class.student_set.count }} Students </a>
</div>

<div class="mx-5 my-2">
    <div class="d-flex mb-2">
        <button class="btn button ms-auto" type="button" data-bs-toggle="modal" data-bs-target="#addGroupModal"> <i class="bi bi-folder-plus"></i> Add Category</button>
    </div>
    {% for group in notes_groups %}
        {% include "organizer/notes_upload.html" with group=group %}
        <div class="accordion list-item mb-5" id="accordian{{group.id}}">
            <div class="accordion-item">
                <h2 class="accordion-header">
                    <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapse{{group.id}}" aria-expanded="false" aria-controls="collapse{{group.id}}">
                      {{ group.title }}
                    </button>
                </h2>
                <div id="collapse{{group.id}}" class="accordion-collapse collapse show list-item" aria-labelledby="heading{{group.id}}" data-bs-parent="#accordian{{group.id}}">
                    <div class="accordion-body">
                        <div class="mb-2">
                            <button class="btn button" id="upload{{group.id}}" type="button" data-bs-toggle="modal" data-bs-target="#uploadModal{{group.id}}">
                                <i class="bi bi-file-earmark-arrow-up"></i> Upload Notes
                            </button>
                        </div>

                        <ul class="list-group">
                            {% for notes in group.notes_set.all %}
                            <li class="list-group-item list-item" id="note{{notes.id}}">
                                <div class="d-flex align-items-center">
                                    <input class="form-check-input" type="checkbox">
                                    <a class="ms-2" href="{{notes.pdf.url}}" target="_blank" rel="noopener noreferrer"> {{notes.title}} </a>
                                    <div class="ms-4">  <i class="bi bi-calendar-check me-1"></i> Uploaded {{ notes.date }} </div>
                                    {% if notes.student == user.student %}
                                        <button class="btn btn-sm button-red button-delete ms-auto" type="button" id="delete{{notes.id}}">  <i class="bi bi-trash"></i> Delete </button>
                                    {% endif %}
                                </div>
                            </li>
                            {% empty %}
                             <li class="list-group-item list-item">
                                 <i class="bi bi-file-earmark-x"></i> No notes uploaded yet
                             </li>
                            {% endfor %}
                        </ul>
                    </div>
               </div>
            </div>
        </div>
    {% empty %}
    <ul class="list-group">
        <li class="list-group-item list-item text-center">
            <i class="bi bi-file-earmark-x"></i> No categories added yet, add a category to upload notes!
        </li>
    </ul>
    {% endfor %}
</div>

{% if class in user.student.schedule.all %}
    <div class="text-center mx-5 my-5">
        <form method ="POST" enctype ="multipart/form-data" action="{% url 'organizer:leave' class.class_name %}">
            {% csrf_token %}
            <button class="btn button-red" > <i class="bi bi-door-open-fill"></i> Leave Class </button>
        </form>
    </div>
{% endif %}

<!-- Add Notes Group Modal -->
<div class="modal fade" id="addGroupModal" tabindex="-1" aria-labelledby="addGroupModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 id="addGroupModalLabel">Add Notes Category</h5>
        <button type="button" class="button-close" data-bs-dismiss="modal" aria-label="Close">
            <i class="bi bi-x"></i>
        </button>
      </div>
      <div class="modal-body d-inline-flex justify-content-center align-items-baseline">
          <form id="addNotesGroupForm">
              {% csrf_token %}
              <input type="text" id="titleInput" placeholder="Title" required="required">
              <button type="submit" class="btn btn-sm button m-1" id="addNotesGroupButton">Add</button>
          </form>
      </div>
    </div>
  </div>
</div>

{% endblock %}

{% block js %}
    <script type="module" src="{% static 'add_notes_group.js' %}"></script>
    <script type="module" src="{% static 'delete_note.js' %}"></script>
    
{% endblock %}

organizer/templates/organizer/home.html
{% extends "organizer/base.html" %}
{% load static %}
{% block styles %}
    <link rel="stylesheet" href="{% static 'home.css' %}">
{% endblock %}
{% block content %}

{% if registered and user.is_authenticated %}
<div class="mx-5 d-flex">
    <button id="jokebtn" type="button" class="btn button rounded-circle btn-lg ms-auto">
        <!-- Joke Generator  -->
        <i class="bi bi-emoji-laughing"></i>
    </button>
</div>


<!-- Modal -->
<div class="modal fade" id="assignModal"  tabindex="-1" aria-labelledby="assignModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="assignModalLabel"></h5>
          <button id="closebtn" type="button" class="button-close float-end" data-bs-dismiss="modal" aria-label="Close">
            <i class="bi bi-x"></i>
          </button>
        </div>
        <div class="modal-body"> 
            <figure class="">
                <blockquote class="blockquote">
                    <p id="joke"></p>
                </blockquote>
                <figcaption id="answer"></figcaption>
            </figure>
      </div>
    </div>
  </div>
  </div>


<div class="text-center mb-5">
    <h1>Upcoming Deadlines</h1>
    <div class="mx-5 my-2">
        {% include "organizer/assignments_list.html" with assignments=assignments %}
    </div>
</div>
<div class="text-center">
    <h1>My Classes</h1>
</div>
<div class="mx-5">
    <ul class="nav nav-tabs">
    <li class="nav-item" >
      <a class="nav-link active" onclick="displayCards()" id="cards-tab">Class Pages <i class="bi bi-grid-fill"></i></a>
    </li>
    <li class="nav-item" >
      <a class="nav-link" onclick="displaySchedule()" id="schedule-tab">Schedule <i class="bi bi-hdd-stack"></i></a>
    </li>
  </ul>
</div>
<div id="classes">
    <div class="text-center mt-2" id="class-cards">
         <!-- display classes -->
        <div class="text-center mx-5">
            <div class="row row-cols-3"> <!-- responsive grid w 3 cols-->
            <!-- display student's classes -->
                {% for class in classes %}
                <a href="{% url 'organizer:classview' class.class_name %}">
                <div class="col mb-3 w-35">
                    <div class="card list-item zoom">
                        <div class="card-body">
                            <h5 class="card-title">{{ class.class_name }} </h5>
                            <p class="card-text">{{ class.student_set.count }} Students</p>
                        </div>
                    </div>
                </div>
                </a>
                {% endfor %}

                <div class="col mb-3 w-35">
                    <a href="{% url 'organizer:search' %}">
                    <div class="card list-item zoom" >
                        <div class="card-body">
                            <h5 class="card-title">Add Class</h5>
                            <h5 class="card-text"><i class="bi bi-plus-square"></i></h5>
                        </div>
                    </div>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="" id="schedule" style="display:none;">
    <div class="mx-5 my-2">
        <h5> Monday </h5>
        {% include "organizer/schedule.html" with day=M %}

        <h5> Tuesday </h5>
        {% include "organizer/schedule.html" with day=T %}

        <h5> Wednesday </h5>
        {% include "organizer/schedule.html" with day=W %}

        <h5> Thursday </h5>
        {% include "organizer/schedule.html" with day=R %}

        <h5> Friday </h5>
        {% include "organizer/schedule.html" with day=F %}
    </div>
</div>
{% else %}
<div class="text-center m-5">
    <a class="btn button" href="{% url 'index' %}">Go to Login Page <i class="bi bi-arrow-right-circle"></i></a>
</div>

{% endif%}
{% endblock %}

{% block js %}
    <script>
        function displaySchedule(){
            document.getElementById("classes").style.display="none";
            document.getElementById("schedule").style.display="block";
            document.getElementById("schedule-tab").classList.add("active");
            document.getElementById("cards-tab").classList.remove("active");
        }

        function displayCards(){
            document.getElementById("schedule").style.display="none";
            document.getElementById("classes").style.display="block";
            document.getElementById("cards-tab").classList.add("active");
            document.getElementById("schedule-tab").classList.remove("active");

        }
    </script>
    <script type="module" src="{% static 'assignment.js' %}"></script>
    <script type="module" src="{% static 'newJoke.js' %}"></script>
    <script type="module" src="{% static 'delete_assign.js' %}"></script>

{% endblock %}

organizer/templates/organizer/join_section.html
<div class="modal fade" id="joinSection{{class.class_name}}" tabindex="-1" aria-labelledby="joinSectionLabel{{class.class_name}}" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="joinSectionLabel{{class.class_name}}"> Join {{ class.class_name }}</h5>
          <button type="button" class="button-close" data-bs-dismiss="modal" aria-label="Close">
            <i class="bi bi-x"></i>
          </button>
        </div>
        <div class="modal-body">
            <form id="joinForm{{class.class_name}}">
                {% csrf_token %}
                <div class="mx-5">
                    <div class="m-2">
                        <label class="me-1"> Section </label>
                        <select class="form-control" name="section">
                          {% for section in class.section_set.all %}
                              <option value="{{ section.id }}"> {{ section }} </option>
                          {% endfor %}
                        </select>
                    </div>
                    <div class="d-flex justify-content-center">
                        <button class="btn button mt-2 join-button" type="button" id="joinSubmit{{class.class_name}}"> Join Class </button>
                    </div>
                </div>
            </form>
        </div>
      </div>
  </div>
</div>

organizer/templates/organizer/schedule.html
<ul class="list-group mb-3">
    {% for class in day %}
        <li class="list-group-item list-item">
            <div class="row">
            <div class="col-3"> <a href="{% url 'organizer:classview' class.course.class_name %}"> {{ class.course.class_name }} </a> | {{ class.professor_lname }} </div>
            <div class="col-6"> {{ class.start_time }} - {{ class.end_time }} </div>
            </div>
        </li>
    {% empty %}
        <li class="list-group-item list-item"> No classes </li>
    {% endfor %}
</ul>