a13project/urls.py
from json.decoder import JSONDecodeError
from django import urls
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

from django.views.generic import TemplateView
from django.contrib.auth.views import LogoutView


from django.http import HttpResponse, HttpResponseRedirect

from django.views import generic
import requests
from django.template import loader

class IndexView(generic.View):
    def index(request):
        template = loader.get_template('index.html')
        quoteText=""
        quoteAuthor=""

        while True:
            try:
                response = requests.get('http://api.forismatic.com/api/1.0/?method=getQuote&format=json&lang=en')
                quote = response.json()
                quoteText = quote['quoteText']
                quoteAuthor = quote['quoteAuthor']
            except JSONDecodeError: #for some reason this api returns lots of decode errors
                continue
            break
        context = {
            'quoteText': quoteText,
            'quoteAuthor': quoteAuthor
        }
        return HttpResponse(template.render(context, request))

urlpatterns = [
    path('organizer/', include('organizer.urls')),  # the app is called organizer so it's intuitive in url
    path('admin/', admin.site.urls),
    path('', IndexView.index, name='index'),
    path('accounts/', include('allauth.urls')),
    path('logout', LogoutView.as_view(), name='logout'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

organizer/urls.py
from django.urls import path
from django.urls.resolvers import URLPattern
from django.conf.urls.static import static
from django.conf import settings

from . import views

app_name = 'organizer'  # set app namespace
urlpatterns = [
    path('', views.HomeView.home, name='home'),  # ex: /organizer/ aka homepage
    # path('login/', views.LoginView.login, name='login'),  # ex: /organizer/login/ aka login page
    # path('register/', views.register_student, name='register'),
    path('register_check/', views.checkIfStudentRegistered, name='check_register'),
    path('students/<str:class_name>/', views.StudentView.studentView, name='students'),
    path('profile/', views.ProfileView.profileView, name='profile'),  # ex: /organizer/profile/ aka profile page
    path('search/', views.SearchView.searchView, name='search'), # /organizer/search/ for class search page
    path('class/<str:class_name>/', views.ClassView.classView, name='classview'),
    path('join/<str:class_name>/', views.JoinClassView, name='join'),
    path('leave/<str:class_name>/', views.LeaveClassView, name='leave'),
    path('assignments/', views.AssignView, name='assignments'),
    path('upload/<int:notes_group>/', views.NotesUploadView, name='upload'),
    path('addGroup/', views.AddNotesGroupView, name='addGroup'),
    path('deletenotes/<int:notes_id>/', views.DeleteNotesView, name='delete_notes'),
    path('check_assignment/<int:assign_id>/', views.CheckAssignView, name='check_assign'),
    path('deleteassignment/<int:assign_id>/', views.DeleteAssignView, name='delete_assign'),
    path('populate/<int:start>/', views.populate_database_view, name='populate'),
    path('newjoke/', views.newJoke, name='joke')


] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/index.html
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- bootstrap -->
  {% load static %}
  {% load bootstrap5 %}
  {% bootstrap_css %}
  {% bootstrap_javascript %}
  {% load socialaccount %}
  <title>UVA Organizer</title>

  <!-- icons -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.6.1/font/bootstrap-icons.css">

  <!-- fonts -->
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Noto+Sans&family=Open+Sans:wght@300&display=swap" rel="stylesheet">

  <!-- jquery -->
  <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/js-cookie@3.0.1/dist/js.cookie.min.js"></script>

  <link rel="stylesheet" href="{% static 'base.css' %}">
  <link rel="stylesheet" href="{% static 'index.css' %}">

  <!-- favicon -->
  <link rel="shortcut icon" type="image/png" href="{% static 'img/favicon.ico' %}"/>
</head>


{% block content %}
    <!-- navbar -->
  <nav class="navbar navbar-expand-lg p-3 d-flex align-items-baseline">
    <h5 class="navbar-brand mb-0"> <i class="bi bi-journal-bookmark-fill"></i> Assignment & Note Organizer</h5>
  </nav>

<div class="text-center">
  <h1> UVA Assignment Organizer </h1>
  <p class="mb-5 lead">
    <i class="bi bi-journal-text"></i> Crowd source class notes.
    <i class="bi bi-check2-square ms-1"></i> Track deadlines.
    <i class="bi bi-clipboard-data ms-1"></i> Ace your classes!
  </p>
  {% if user.is_authenticated %}
    <h5 class="mb-4">Welcome, {{ user.username }}!</h5>
    <a class="btn button" href="{% url 'organizer:check_register' %}"> View Your Dashboard <i class="bi bi-arrow-right-circle"></i> </a>
  {% else %}
    <a class="btn button" href="{% provider_login_url 'google' %}"><i class="bi bi-google"></i> Login With Google</a>
  {% endif %}


<!-- Motivational Quote -- Refresh the page a new one -->
  <figure class="quote-box mb-3 p-2 fixed-bottom">
    <blockquote>
       <p>"{{quoteText}}"</p>
    </blockquote>
    {% if quoteAuthor %}
    <figcaption class="blockquote-footer">
      {{quoteAuthor}}
    </figcaption>
    {% endif %}
  </figure>
</div>
{% endblock %}